---
- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Install CLI programs (apt)
  become: yes
  apt:
      name:
        - zsh
        - aria2
        - ranger
        - htop
        - python3-pip
        - newsboat
        - r-base
        - fzf
        - ripgrep
        - stow
        - tmux
        - tmuxinator
        - tmux-plugin-manager
        - tree
        - mlocate

- name: Install CLI programs (pip)
  pip:
    name: youtube-dl

- name: Install GUI programs (apt)
  become: yes
  apt:
      name:
        - mpv
        - firefox
        - timeshift
        - transmission
        - spotify-client
        - deja-dup
        - rhythmbox
        - thunderbird
        - shotwell

- name: Install GUI programs (snap)
  become: yes
  snap:
      name:
        - telegram-desktop
        - multipass
  when: ansible_facts['distribution'] == 'Ubuntu'

