---
- name: Install virtualization software
  become: yes
  apt:
      name:
        - qemu-kvm
        - libvirt-daemon-system
        - ibvirt-clients
        - bridge-utils
        - virt-manager

- name: Install firewall
  become: yes
  apt:
      name:
        - ufw
        - gufw

- name: Install Apparmor
  become: yes
  apt:
      name:
        - apparmor-profiles
        - apparmor-utils
